SELECT *
  FROM [DataWarehouse].[gold].[fact_sales]


  SELECT *
  FROM [DataWarehouse].[gold].[dim_prodcut]

  SELECT *
  FROM [DataWarehouse].[gold].[dim_customer]

-- explore all objects in database 
  select * from information_schema.tables


 -- explore all column in database 
	select * 
	from information_schema.columns

	where table_schema='gold'

-- explore the dimensions see the unique in each dim 
-- country in customer dim 
select distinct country 
from gold.dim_customer

-- explore the categories and subcategory in prodcut dimensions 
select distinct category_name,subcategory_name,prodcut_name
from gold.dim_prodcut

-- explore the date column 
-- identify the earliest and latest dates boundaris 
-- understand the scope of date and the tiemspan 
-- dim_customer	birthdate
-- dim_customer	create_date
-- dim_prodcut	start_date
-- fact_sales	order_date
-- fact_sales	ship_date
-- fact_sales	due_ship_date

--boundary of order date and ship date 
select min(order_date) as first_order_date,
max(order_date) as last_order_date , 
min(ship_date) as first_ship_date,
max(ship_date) as last_ship_date,
datediff(year,min(order_date),max(order_date)) as order_range_year
from gold.fact_sales

-- find the youngest and oldest customer 
-- in the silver layer we replace the null values with 1900 
select
    min(birthdate) as oldest_customer,
    max(birthdate) as youngest_customer,
	datediff(year,min(birthdate),getdate()) as oldest_age,
	datediff(year,max(birthdate),getdate()) as youngest_age
from gold.dim_customer
where birthdate > '1900-01-01'
  and birthdate <= getdate()

-- measured exploreed 

-- 1.find the total sales 
select sum(sales_amount)
from gold.fact_sales

-- 2.find how many tiems are sold 
select sum(quantity)
from gold.fact_sales

-- 3.find the average slling price 
select avg(price)
from gold.fact_sales
-- 4.find the totoal number of orders 
select count(distinct order_number)
from gold.fact_sales
-- 5.find the total number of products 
select count(distinct product_key)
from gold.dim_prodcut
-- 6.find the total number of customers 
select count(distinct customer_key)
from gold.dim_customer
-- 7.find the total number of customers that has placed an order 
select count(distinct customer_key) 
from gold.fact_sales



-- magnitude (measuer by dimensions)

-- 1. find total customers by countries 
select count(distinct customer_key ) as total_customer_by_country ,country
from gold.dim_customer
group by country
-- 2. find total cusotmers by gender 
select count( customer_key ) as total_customer_by_gender ,gender
from gold.dim_customer
group by gender
-- 3 find total products by category 
select count(distinct product_key ) as total_product_by_category ,category_name
from gold.dim_prodcut
group by category_name
-- 4. what is the average cost in each category 
select avg( prodcut_cost ) as average_productcost_by_category ,category_name
from gold.dim_prodcut
group by category_name

-- 5. what is the total revenue generated for each categorey 
select pd.category_name , sum(fc.sales_amount) as total_revenue_by_category
from gold.fact_sales as fc
join gold.dim_prodcut as pd on pd.product_key=fc.product_key
group by pd.category_name

-- 6. find total revenue is generated by each customer 
select dc.customer_key,dc.first_name, sum(fc.sales_amount) as total_revenue_customer
from gold.fact_sales as fc
join gold.dim_customer as dc on dc.customer_key=fc.customer_key
group by dc.customer_key,dc.first_name
order by total_revenue_customer desc
-- 7.what is the distribution of sold items accross countries 
select dc.country, sum(fc.quantity) as quantity_by_countries
from gold.fact_sales as fc
join gold.dim_customer as dc on dc.customer_key=fc.customer_key
group by dc.country

-- ranking 
-- which 5 products generate the hghest revenue 

select top 5
row_number() over (order by sum(fc.sales_amount) desc) as product_rank,
pd.prodcut_name,sum(fc.sales_amount) as sales_amount
from gold.fact_sales as fc
join gold.dim_prodcut as pd on fc.product_key = pd.product_key
group by pd.product_key, pd.prodcut_name

-- what are the 5 worst prforming prodcut in terms of sales 
select top 5
row_number() over (order by sum(fc.sales_amount)) as product_rank,
pd.prodcut_name,sum(fc.sales_amount) as sales_amount
from gold.fact_sales as fc
join gold.dim_prodcut as pd on fc.product_key = pd.product_key
group by pd.product_key, pd.prodcut_name

-- find the top 10 customers who have generated the highest revenue 
select top 10
row_number() over (order by sum(fc.sales_amount)desc) as customer_rank,
dc.first_name,sum(fc.sales_amount) as sales_amount
from gold.fact_sales as fc
join gold.dim_customer as dc on fc.customer_key = dc.customer_key
group by dc.customer_key, dc.first_name
